### PR TITLE
Use simple_form for messages form

### PR DESCRIPTION
**Pull request by jessieay**
**Why**:
* SimpleForm uses HTML5 so modern browsers won't let users submit
invalid messages
* Browsers without HTML5 will still show a flash message
* This adds a spec for flash messages, too

Before:

screen shot 2017-03-02 at 4 02 10 pm

After:

with HTML 5 browser:

screen shot 2017-03-02 at 4 06 55 pm

without HTML 5 browser:

screen shot 2017-03-02 at 3 58 31 pm

NOTE I removed unused alerts icons here for clarity. We still need to add a new error icon since the current one (from USWDS) is huge.

### CODE REVIEW

**Comment by jessieay** [comment]
hey @amoose it looks like you began a review but did not finish -- thoughts on this change?

**Comment by line47** [comment]
Hey @jessieay would this also work for the Views and Hours text boxes?

**Comment by jessieay** [comment]
@line47 yes, although it is not possible to simulate a scenario where those are `nil` because the form already enforces that there is an integer in there

**Comment by line47** [comment]
@jessieay it does force a default entry but the user can still delete and then try to submit the form

**Comment by jessieay** [comment]
@line47 if we add presence validations for those, simple_form should enforce. will add

**Comment by jessieay** [comment]
@line47  added presence validations at 43d66cf

**Comment by line47** [comment]
I'm seeing an issue where a "*" is added to the UI. Also it looks like the text area is not showing the HTML5 input error as expected.

screen shot 2017-03-07 at 3 02 19 pm

**Comment by jessieay** [comment]
yes that star comes from simple form to indicate required fields. We can remove.

**Comment by line47** [comment]
Yeah, I'd just rather remove it. 👍

**Comment by jessieay** [comment]
@line47 updated! 

screen shot 2017-03-07 at 1 36 45 pm

screen shot 2017-03-07 at 1 36 40 pm

**Comment by jessieay** [comment]
This is what the whole form looks like now:

screen shot 2017-03-07 at 1 42 06 pm

**Pull request merged**
