### PR TITLE
Upgrade to Ruby 2.3.5 and rebundle with bundler 1.16 pre

### PR DESCRIPTION
**Pull request by jgrevich**

### CODE REVIEW

**Comment by amoose** [comment]
👀 testing with cloud.gov...

**Comment by amoose** [comment]
Might as well go with 2.4.2 -- which, requires some other upgrades.

**Comment by amoose** [comment]
OK-- tested with Ruby 2.4.2. I had to make the following Rails upgrade: 

```
diff --git a/Gemfile b/Gemfile
index a102fc6..84b6bba 100644
--- a/Gemfile
+++ b/Gemfile
@@ -2,7 +2,7 @@ source 'https://rubygems.org'
 git_source(:github) { |repo_name| "https://github.com/#{repo_name}.git" }

 # Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
-gem 'rails', '~> 4.2.7.1'
+gem 'rails', '~> 4.2.7'

 gem 'autoprefixer-rails'
 gem 'sass-rails'
diff --git a/Gemfile.lock b/Gemfile.lock
index 6c7aab1..9e82644 100644
--- a/Gemfile.lock
+++ b/Gemfile.lock
@@ -1,61 +1,60 @@
 GIT
-  remote: git://github.com/18F/uswds-rails-gem.git
+  remote: https://github.com/18F/uswds-rails-gem.git
   revision: aa12ddd314209ef9e75bb2f2bfcf1454336df049
   specs:
     uswds-rails (1.0.0)
       sass

 GIT
-  remote: git://github.com/matschaffer/knife-solo.git
-  revision: d51ebaa1391937e4613672d31da2a040d054d78d
+  remote: https://github.com/matschaffer/knife-solo.git
+  revision: 98a4d7f08cbd6b053a6c580faab1babc1c390958
   submodules: true
   specs:
-    knife-solo (0.5.2)
+    knife-solo (0.7.0.pre)
       chef (>= 10.20)
       erubis (~> 2.7.0)
-      net-ssh (~> 2.7, < 3.0)
+      net-ssh (>= 2.7)

 GEM
   remote: https://rubygems.org/
   specs:
     CFPropertyList (2.3.2)
-    actionmailer (4.2.7.1)
-      actionpack (= 4.2.7.1)
-      actionview (= 4.2.7.1)
-      activejob (= 4.2.7.1)
+    actionmailer (4.2.10)
+      actionpack (= 4.2.10)
+      actionview (= 4.2.10)
+      activejob (= 4.2.10)
       mail (~> 2.5, >= 2.5.4)
       rails-dom-testing (~> 1.0, >= 1.0.5)
-    actionpack (4.2.7.1)
-      actionview (= 4.2.7.1)
-      activesupport (= 4.2.7.1)
+    actionpack (4.2.10)
+      actionview (= 4.2.10)
+      activesupport (= 4.2.10)
       rack (~> 1.6)
       rack-test (~> 0.6.2)
       rails-dom-testing (~> 1.0, >= 1.0.5)
       rails-html-sanitizer (~> 1.0, >= 1.0.2)
-    actionview (4.2.7.1)
-      activesupport (= 4.2.7.1)
+    actionview (4.2.10)
+      activesupport (= 4.2.10)
       builder (~> 3.1)
       erubis (~> 2.7.0)
       rails-dom-testing (~> 1.0, >= 1.0.5)
-      rails-html-sanitizer (~> 1.0, >= 1.0.2)
-    activejob (4.2.7.1)
-      activesupport (= 4.2.7.1)
+      rails-html-sanitizer (~> 1.0, >= 1.0.3)
+    activejob (4.2.10)
+      activesupport (= 4.2.10)
       globalid (>= 0.3.0)
-    activemodel (4.2.7.1)
-      activesupport (= 4.2.7.1)
+    activemodel (4.2.10)
+      activesupport (= 4.2.10)
       builder (~> 3.1)
-    activerecord (4.2.7.1)
-      activemodel (= 4.2.7.1)
-      activesupport (= 4.2.7.1)
+    activerecord (4.2.10)
+      activemodel (= 4.2.10)
+      activesupport (= 4.2.10)
       arel (~> 6.0)
-    activesupport (4.2.7.1)
+    activesupport (4.2.10)
       i18n (~> 0.7)
-      json (~> 1.7, >= 1.7.7)
       minitest (~> 5.1)
       thread_safe (~> 0.3, >= 0.3.4)
       tzinfo (~> 1.1)
     addressable (2.3.8)
-    arel (6.0.3)
+    arel (6.0.4)
     autoprefixer-rails (6.3.1)
       execjs
       json
@@ -163,7 +162,7 @@ GEM
       coffee-script-source
       execjs
     coffee-script-source (1.10.0)
-    concurrent-ruby (1.0.2)
+    concurrent-ruby (1.0.5)
     connection_pool (2.2.0)
     coveralls (0.7.1)
       multi_json (~> 1.3)
@@ -173,6 +172,7 @@ GEM
       thor
     crack (0.4.3)
       safe_yaml (~> 1.0.0)
+    crass (1.0.2)
     daemons (1.2.3)
     database_cleaner (1.5.1)
     debug_inspector (0.0.2)
@@ -291,8 +291,8 @@ GEM
       fog-core
       nokogiri (~> 1.5, >= 1.5.11)
     formatador (0.2.5)
-    globalid (0.3.7)
-      activesupport (>= 4.1.0)
+    globalid (0.4.1)
+      activesupport (>= 4.2.0)
     gssapi (1.2.0)
       ffi (>= 1.0.1)
     guard (2.13.0)
@@ -316,14 +316,15 @@ GEM
       builder (>= 2.1.2)
     haml (4.0.7)
       tilt
-    hashdiff (0.2.3)
+    hashdiff (0.3.7)
     hashie (2.1.2)
     highline (1.7.8)
     hitimes (1.2.3)
     http-cookie (1.0.2)
       domain_name (~> 0.5)
     httpclient (2.7.1)
-    i18n (0.8.1)
+    i18n (0.9.0)
+      concurrent-ruby (~> 1.0)
     inch (0.7.0)
       pry
       sparkr (>= 0.2.0)
@@ -351,19 +352,20 @@ GEM
     logging (2.0.0)
       little-plugger (~> 1.1)
       multi_json (~> 1.10)
-    loofah (2.0.3)
+    loofah (2.1.1)
+      crass (~> 1.0.2)
       nokogiri (>= 1.5.9)
     lumberjack (1.0.10)
-    mail (2.6.4)
+    mail (2.6.6)
       mime-types (>= 1.16, < 4)
     method_source (0.8.2)
     mime-types (2.99.3)
     mini_portile2 (2.3.0)
     minitar (0.5.4)
-    minitest (5.10.1)
+    minitest (5.10.3)
     mixlib-authentication (1.3.0)
       mixlib-log
-    mixlib-cli (1.5.0)
+    mixlib-cli (1.7.0)
     mixlib-config (2.2.1)
     mixlib-log (1.6.0)
     mixlib-shellout (2.2.6)
@@ -415,7 +417,7 @@ GEM
       slop (~> 3.4)
     pry-nav (0.2.4)
       pry (>= 0.9.10, < 0.11.0)
-    puma (3.6.0)
+    puma (3.10.0)
     quiet_assets (1.1.0)
       railties (>= 3.1, < 5.0)
     rack (1.6.8)
@@ -423,16 +425,16 @@ GEM
       rack
     rack-test (0.6.3)
       rack (>= 1.0)
-    rails (4.2.7.1)
-      actionmailer (= 4.2.7.1)
-      actionpack (= 4.2.7.1)
-      actionview (= 4.2.7.1)
-      activejob (= 4.2.7.1)
-      activemodel (= 4.2.7.1)
-      activerecord (= 4.2.7.1)
-      activesupport (= 4.2.7.1)
+    rails (4.2.10)
+      actionmailer (= 4.2.10)
+      actionpack (= 4.2.10)
+      actionview (= 4.2.10)
+      activejob (= 4.2.10)
+      activemodel (= 4.2.10)
+      activerecord (= 4.2.10)
+      activesupport (= 4.2.10)
       bundler (>= 1.3.0, < 2.0)
-      railties (= 4.2.7.1)
+      railties (= 4.2.10)
       sprockets-rails
     rails-deprecated_sanitizer (1.0.3)
       activesupport (>= 4.2.0.alpha)
@@ -447,9 +449,9 @@ GEM
       rails_stdout_logging
     rails_serve_static_assets (0.0.5)
     rails_stdout_logging (0.0.5)
-    railties (4.2.7.1)
-      actionpack (= 4.2.7.1)
-      activesupport (= 4.2.7.1)
+    railties (4.2.10)
+      actionpack (= 4.2.10)
+      activesupport (= 4.2.10)
       rake (>= 0.8.7)
       thor (>= 0.18.1, < 2.0)
     rake (10.5.0)
@@ -581,7 +583,7 @@ GEM
     sprockets (3.7.1)
       concurrent-ruby (~> 1.0)
       rack (> 1, < 3)
-    sprockets-rails (3.2.0)
+    sprockets-rails (3.2.1)
       actionpack (>= 4.0)
       activesupport (>= 4.0)
       sprockets (>= 3.0.0)
@@ -595,7 +597,7 @@ GEM
       daemons (~> 1.0, >= 1.0.9)
       eventmachine (~> 1.0, >= 1.0.4)
       rack (~> 1.0)
-    thor (0.19.4)
+    thor (0.20.0)
     thread_safe (0.3.6)
     tilt (2.0.6)
     timecop (0.8.0)
@@ -604,7 +606,7 @@ GEM
     tins (1.8.2)
     turbolinks (2.5.3)
       coffee-rails
-    tzinfo (1.2.2)
+    tzinfo (1.2.4)
       thread_safe (~> 0.1)
     uglifier (2.7.2)
       execjs (>= 0.3.0)
@@ -617,7 +619,7 @@ GEM
     varia_model (0.4.1)
       buff-extensions (~> 1.0)
       hashie (>= 2.0.2, < 4.0.0)
-    webmock (1.22.6)
+    webmock (3.1.0)
       addressable (>= 2.3.6)
       crack (>= 0.3.2)
       hashdiff
@@ -668,7 +670,7 @@ DEPENDENCIES
   pry-nav
   puma
   quiet_assets
-  rails (~> 4.2.7.1)
+  rails (~> 4.2.7)
   rails_12factor
   rb-fsevent
   rspec-collection_matchers
@@ -694,4 +696,4 @@ DEPENDENCIES
   webmock
```

PR coming soon! 🏁

**Comment by jgrevich** [comment]
Cool with me, let's just go straight to 242

**Comment by amoose** [comment]
Closing in favor of new PR with 2.4.2

**Pull request closed without merging**
